version: '3.8'
services:
  app:
    build:
      context: .
    ports:
      - '3000:3000'
    networks:
      - lingomate
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn start:dev
networks:
  lingomate: